coverage:
  ignore:
    - tests
  status:
    project:
      default:
        informational: true  # doc: https://docs.codecov.com/docs/commit-status#informational
        target: 80%  # 要求整体覆盖率 >=80%
        threshold: 1%  # 允许比目标低 1%（79% 会失败）
    patch:
      default:
        informational: true
        target: 80%  # PR 修改的代码覆盖率要求
