name: Cpp Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cpplint:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Cpp Lint Check
        run: |
          pip install cpplint
          cpplint --recursive src/ include/
      - name: Trigger Build
        if: success()
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: cpplint_success
