name: Cpp Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cpplint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Cpp Lint Check
        run: |
          python3 tools/cpplint/cpplint.py --recursive src/ include/
