name: CppLint Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cpplint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |  # 示例：运行 cpplint
          pip install cpplint
          cpplint --recursive src/ include/
